### ISSUE TITLE
Unable to get hooks value after enabling plugin

### ISSUE THREAD

**Issue by DataEngg** [emqtt/emq-plugin-template#2]
I have enabled the emqttd_plugin_template in the broker but how would I get the metrics from a broker as described in plugins description.

**Description of plugin is-**

The plugin could register callbacks for hooks. The hooks will be run by the broker when a client connected/disconnected, a topic subscribed/unsubscribed or a message published/delivered:

client.connected    Run when a client connected to the broker successfully
client.subscribe    Run before a client subscribes topics
client.subscribe.after  Run after a client subscribed topics
client.unsubscribe  Run when a client unsubscribes topics
message.publish Run when a message is published
message.delivered   Run when a message is delivered
message.acked   Run when a message(qos1/2) is acked
client.disconnected Run when a client is disconnnected

Problem - According to the description, I am unable to get the metrics information from a broker like when the client connected , client disconnected, message published, message delivered and message acknowledged.

**Comment by huangdan** [comment]
dashboard  show the metric info
